# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: mercure

# The type of the application to build.
type: golang:1.18

# The internal folder where the app can be found
source:
    root: mercure/mercure-submodule/.config

# The toolstack used to build the application.
build:
  flavor: none

variables:
  env:
    MERCUREVERSION: 0.14.4
    SERVER_NAME: ":8888"
    MERCURE_TRANSPORT_URL: "bolt:///var/run/mercure.db?size=1000&cleanup_frequency=0.5"
    MERCURE_EXTRA_DIRECTIVES: |
      cors_origin *
      publish_origins *
      subscriptions
      demo
    GLOBAL_OPTIONS: |
      auto_https off
    MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
    MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"

disk: 2048
size: L

mounts:
  "database": { source: local, source_path: "database" }
  "/.local": { source: local, source_path: .local }
  "/.config": { source: local, source_path: .config }

hooks:
    build: |
      #Install Mercure using cache
      echo "${MERCUREVERSION}"
      FILE="mercure_${MERCUREVERSION}_Linux_x86_64.tar.gz"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
        URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
        echo "Downloading $URL"
        wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
        echo "Found $FILE in cache, using cache"
      fi
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE
web:
    commands:
        start: ./mercure run --config Caddyfile.platform_sh
    locations:
        /:
            allow: true
            scripts: false
            passthru: true
            request_buffering:
              enabled: false
